def get_user_name():
    public_user_li = [
       # {"user_id": "sora.neverforget8964.org", "author": "中出羊子"},
        {"user_id": "JayChengManKit", "author": "鄭文杰議員 JC"},
        {"user_id": "VincentChengKengIeong", "author": "觀塘區議員．鄭景陽 Vincent Cheng Keng Ieong"},
        {"user_id": "sunnychiuchupong", "author": "趙柱幫【幫您發聲】"},
        {"user_id": "fanlingfranco", "author": "張正皓。Franco Cheung"},
        #{"user_id": "張培剛專頁-111083827267803", "author": "張培剛專頁"},
        {"user_id": "ChingDPHK", "author": "張茂清 Cheung Mau Ching ‧ 變革慈雲山"},
        {"user_id": "yick.angus", "author": "易承聰 Angus Yick"},
        #{"user_id": "葉梓傑-1126993467352031", "author": "葉梓傑"},
        #{"user_id": "顏汶羽Frankie-Ngan-1718244738276438", "author": "顏汶羽Frankie Ngan"},
        {"user_id": "SINCheukNamDPHK", "author": "冼卓嵐 SIN Cheuk Nam"},
        {"user_id": "sinhofaihenry", "author": "Henry Sin 冼豪輝"},
        #{"user_id": "janet.ng.5074", "author": "伍月蘭"},
        {"user_id": "hysanhinwangng", "author": "伍軒宏·耀祐 Hysan Ng"},
        {"user_id": "Ngtinglam", "author": "吳定霖 Ng Ting Lam"},
        {"user_id": "wongpitmantsingyi", "author": "王必敏（青衣島民）"},
        {"user_id": "shekwilliamofficial", "author": "Shek William 石威廉"},
        {"user_id": "rosandamok", "author": "莫嘉嫻 Mok ka-han, Rosanda"},
        {"user_id": "ChoiHungSSA", "author": "DC Sean Mock office, Chessa 彩虹邨服務聯會 - 莫灝哲議員辦事處"},
        {"user_id": "lawtingtak", "author": "羅庭德 Jasper Law"},
        #{"user_id": "loyuenting1", "author": "盧婉婷"},
        {"user_id": "CaryLoChunYu", "author": "盧俊宇（Cary）樂翠區專頁 - 海翠花園、啟豐園、美樂花園、龍鼓灘"},
       # {"user_id": "100011319554428", "author": "盧德明"},
        {"user_id": "lamtingw", "author": "林廷衞Lam Ting Wai"},
        {"user_id": "matthewclam", "author": "瑞華- 林進 Lam Chun"},
        {"user_id": "hunghomdab", "author": "林德成議員辦事處"},
        #{"user_id": "梁永權-扎根安蔭-革新議會-111735590346189", "author": "梁永權 扎根安蔭 革新議會"},
        {"user_id": "100000102194200", "author": "梁騰丰"},
        {"user_id": "kwuntongfuture", "author": "觀塘願景 - 梁凱晴 Jannelle R. Leung"},
        #{"user_id": "梁嘉銘-108323777399689", "author": "梁嘉銘"},
        {"user_id": "leungkwokho01", "author": "梁國豪 Leung Kwok Ho Super"},
        {"user_id": "howardleehonting", "author": "利瀚庭 Howard Lee Hon Ting"},
        {"user_id": "timothylee.hk", "author": "李軒朗 Timothy Lee"},
        {"user_id": "jackylaimingchak", "author": "黎銘澤 Jacky Lai"},
        {"user_id": "lai.alfredhk", "author": "黎駿穎 屯門市中心 Alfred Lai Chun Wing"},
        {"user_id": "laimanfaiservice", "author": "賴文輝議員辦事處"},
        {"user_id": "yantinapple", "author": "賴嘉汶Apple"},
        #{"user_id": "tungtung.kan", "author": "簡銘東"},
        #{"user_id": "100010798068638", "author": "黃學禮"},
        {"user_id": "leticiawmh", "author": "黃文萱 Leticia Wong"},
        {"user_id": "hongkonger.why", "author": "黃凱盈 Irene"},
        {"user_id": "WongHoFungKen", "author": "黃浩鋒 - 沙田 下城門"},
        {"user_id": "nichonoffical", "author": "韓俊賢 Nicholas Hon Chun Yin"},
        {"user_id": "kwoklongfungofficialpage", "author": "Kwok Long Fung 郭㙟豐"},
        {"user_id": "jodykwokntasdab", "author": "郭芙蓉 Jody Kwok"},
        {"user_id": "civicpartyhk", "author": "公民黨 Civic Party"},
       # {"user_id": "twsykot", "author": "葛兆源"},
        {"user_id": "eastweekfengshui", "author": "東周網 - 玄機"},
        {"user_id": "richardccchan", "author": "陳振哲 Richard Chan"},
        {"user_id": "mozamtung.chan", "author": "陳運通 Mozam"},
        {"user_id": "chantreefai", "author": "洪福陳樹暉 Chan Shu Fai"},
        {"user_id": "chankimkam", "author": "陳劍琴Chan Kim Kam"},
        {"user_id": "LMtsangkamwing", "author": "龍門居民 曾錦榮"},
        {"user_id": "jasoncdab", "author": "莊展銘 JASON"},
        {"user_id": "winfieldchongwingfai", "author": "莊榮輝Winfield"},
        #{"user_id": "周卓然-Nathan-Chau-2235777456734589", "author": "周卓然 Nathan Chau"},
        {"user_id": "raychow.nwsc", "author": "周偉雄Ray Chow"},
        {"user_id": "eunicechau.cp", "author": "Eunice Chau 周琬雯"},
        {"user_id": "agneschowting", "author": "周庭Agnes Chow Ting"},
        {"user_id": "chengszelutpage", "author": "鄭司律 CHENG SZE LUT"},
        {"user_id": "4eyesbro", "author": "鄭錦滿"},
        {"user_id": "WyranCCP", "author": "鄭捷彬 Wyran Cheng"},
        {"user_id": "yankaiwing", "author": "甄啟榮 - 阿甄"},
        {"user_id": "howardchaohk", "author": "趙式浩 Howard Chao"},
        {"user_id": "Jesuslovesjoycechiu", "author": "趙佩玉Joyce Chiu"},
        #{"user_id": "趙寶琴Lucia-625479274539379", "author": "趙寶琴Lucia"},
        {"user_id": "wainamwf", "author": "張偉楠"},
        {"user_id": "yautongkt", "author": "張琪騰 (Jack)"},
        #{"user_id": "張愛羚-Eling-Cheung-114347406951226", "author": "張愛羚 Eling Cheung"},
        {"user_id": "audrey.euyuetmee", "author": "Audrey Eu 余若薇"},
        {"user_id": "TerryYipTuenMun", "author": "葉文斌"},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
        {"user_id": "", "author": ""},
    ]